import {
  AlignLeft,
  ArrowUpToLine,
  BarChart2,
  Baseline,
  BoxSelect,
  CaseSensitive,
  ClipboardList,
  Contrast,
  Eraser,
  Eye,
  FileText,
  Flame,
  FlaskConical,
  Grid2X2,
  ImagePlay,
  ListOrdered,
  Map,
  Minimize,
  PaintBucket,
  Pipette,
  QrCode,
  RefreshCw,
  Ruler,
  ScanLine,
  Search,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  TextCursor,
  Type,
  Zap,
} from "lucide-react";
import type { Tool } from "./types";

export const toolsRegistry: Tool[] = [
  // ── Branding ────────────────────────────────────────────────────────────────
  {
    id: "palette-extractor",
    name: "Extractor de Paleta",
    description: "Extrae la paleta de colores de cualquier imagen.",
    category: "Branding",
    icon: Pipette,
    route: "/tools/palette-extractor",
    status: "stable",
    privacy: "local",
    tags: ["branding", "color", "paleta", "extractor"],
  },
  {
    id: "color-scale-generator",
    name: "Escalas de Color",
    description: "Genera escalas de color armoniosas para tu sistema de marca.",
    category: "Branding",
    icon: SlidersHorizontal,
    route: "/tools/color-scale-generator",
    status: "stable",
    privacy: "local",
    tags: ["branding", "color", "escala", "generador"],
  },
  {
    id: "gradient-generator",
    name: "Gradientes",
    description: "Crea y exporta gradientes CSS para tu identidad visual.",
    category: "Branding",
    icon: PaintBucket,
    route: "/tools/gradient-generator",
    status: "stable",
    privacy: "local",
    tags: ["branding", "gradiente", "css", "color"],
  },
  {
    id: "favicon-generator",
    name: "Generador de Favicons",
    description: "Genera todos los formatos de favicon (PNG e .ico) desde una imagen.",
    category: "Branding",
    icon: BoxSelect,
    route: "/tools/favicon-generator",
    status: "beta",
    privacy: "local",
    tags: ["branding", "favicon", "logo", "generador"],
  },
  {
    id: "copy-assistant",
    name: "Asistente de Copy",
    description: "Tu experto en copywriting de marca, 100% local y privado.",
    category: "Branding",
    icon: Sparkles,
    route: "/tools/copy-assistant",
    status: "stable",
    privacy: "local",
    tags: ["branding", "copy", "escritura", "voz", "ai"],
  },

  // ── UX ──────────────────────────────────────────────────────────────────────
  {
    id: "heatmap-analyzer",
    name: "Heatmap Analyzer",
    description: "Análisis de atención visual predictiva para diseños.",
    category: "UX",
    icon: Flame,
    route: "/tools/heatmap-analyzer",
    status: "beta",
    privacy: "local",
    tags: ["ux", "heatmap", "visual", "analisis", "atencion"],
  },
  {
    id: "journey-map",
    name: "Journey Map",
    description:
      "Construye mapas de viaje del usuario con emociones, touchpoints y oportunidades.",
    category: "UX",
    icon: Map,
    route: "/tools/journey-map",
    status: "stable",
    privacy: "local",
    tags: ["ux", "journey", "mapa", "usuario", "experiencia"],
  },
  {
    id: "mockup-generator",
    name: "Mockups",
    description: "Genera mockups de dispositivos para presentar tus diseños.",
    category: "UX",
    icon: Smartphone,
    route: "/tools/mockup-generator",
    status: "stable",
    privacy: "local",
    tags: ["ux", "mockup", "presentacion", "dispositivo"],
  },

  // ── UI ──────────────────────────────────────────────────────────────────────
  {
    id: "contrast-checker",
    name: "Contraste",
    description: "Verifica el contraste entre colores para accesibilidad WCAG.",
    category: "UI",
    icon: Contrast,
    route: "/tools/contrast-checker",
    status: "stable",
    privacy: "local",
    tags: ["ui", "color", "contraste", "accesibilidad", "wcag"],
  },
  {
    id: "color-blindness",
    name: "Simulador de Daltonismo",
    description:
      "Simula cómo se ven imágenes y paletas con los 8 tipos de daltonismo.",
    category: "UI",
    icon: Eye,
    route: "/tools/color-blindness",
    status: "beta",
    privacy: "local",
    tags: [
      "ui",
      "accesibilidad",
      "daltonismo",
      "color",
      "a11y",
      "contraste",
      "wcag",
    ],
  },
  {
    id: "typography-scale",
    name: "Escala Tipográfica",
    description: "Genera escalas tipográficas modulares con ratios clásicos.",
    category: "UI",
    icon: TextCursor,
    route: "/tools/typography-scale",
    status: "stable",
    privacy: "local",
    tags: ["ui", "tipografia", "escala", "tokens", "sistema"],
  },
  {
    id: "spacing-scale",
    name: "Escala de Espaciado",
    description:
      "Genera sistemas de espaciado exportables como CSS, Tailwind o tokens.",
    category: "UI",
    icon: Ruler,
    route: "/tools/spacing-scale",
    status: "stable",
    privacy: "local",
    tags: ["ui", "espaciado", "spacing", "tokens", "tailwind", "sistema"],
  },
  {
    id: "redline-spec",
    name: "Redline Spec",
    description:
      "Genera especificaciones de handoff para ingeniería con medidas y estilos.",
    category: "UI",
    icon: ScanLine,
    route: "/tools/redline-spec",
    status: "stable",
    privacy: "local",
    tags: ["ui", "handoff", "especificacion", "ingenieria", "medidas"],
  },
  {
    id: "placeholder-generator",
    name: "Placeholders",
    description: "Crea imágenes de relleno con dimensiones exactas.",
    category: "UI",
    icon: ImagePlay,
    route: "/tools/placeholder-generator",
    status: "stable",
    privacy: "local",
    tags: ["ui", "placeholder", "imagen", "relleno"],
  },
  {
    id: "lorem-ipsum",
    name: "Generador Lorem Ipsum",
    description: "Genera texto de relleno personalizado para tus diseños.",
    category: "UI",
    icon: AlignLeft,
    route: "/tools/lorem-ipsum",
    status: "stable",
    privacy: "local",
    tags: ["ui", "texto", "lorem", "relleno"],
  },
  {
    id: "background-remover",
    name: "Remover Fondo",
    description: "Elimina fondos de imágenes de forma automática.",
    category: "UI",
    icon: Eraser,
    route: "/tools/background-remover",
    status: "beta",
    privacy: "local",
    tags: ["ui", "imagen", "fondo", "remover", "asset"],
  },
  {
    id: "image-compressor",
    name: "Comprimir Imagen",
    description: "Reduce el peso de tus imágenes sin perder calidad.",
    category: "UI",
    icon: Minimize,
    route: "/tools/image-compressor",
    status: "stable",
    privacy: "local",
    tags: ["ui", "imagen", "comprimir", "optimizar", "asset"],
  },
  {
    id: "format-converter",
    name: "Convertir Formato",
    description: "Convierte imágenes entre diferentes formatos.",
    category: "UI",
    icon: RefreshCw,
    route: "/tools/format-converter",
    status: "stable",
    privacy: "local",
    tags: ["ui", "imagen", "formato", "convertir", "asset"],
  },
  {
    id: "image-upscaler",
    name: "Upscaler",
    description: "Aumenta la resolución de tus imágenes.",
    category: "UI",
    icon: ArrowUpToLine,
    route: "/tools/image-upscaler",
    status: "stable",
    privacy: "local",
    tags: ["ui", "imagen", "resolucion", "upscaler", "asset"],
  },
  {
    id: "svg-optimizer",
    name: "Optimizador SVG",
    description: "Limpia y minimiza tus archivos SVG.",
    category: "UI",
    icon: Zap,
    route: "/tools/svg-optimizer",
    status: "stable",
    privacy: "local",
    tags: ["ui", "svg", "optimizar", "asset"],
  },
  {
    id: "icon-finder",
    name: "Buscador de Iconos",
    description:
      "Busca y copia iconos SVG de Lucide, Heroicons, Tabler, Phosphor y más.",
    category: "UI",
    icon: Search,
    route: "/tools/icon-finder",
    status: "stable",
    privacy: "server",
    tags: [
      "ui",
      "iconos",
      "svg",
      "lucide",
      "heroicons",
      "tabler",
      "phosphor",
      "iconify",
    ],
  },
  {
    id: "font-finder",
    name: "Buscador de Tipografías",
    description:
      "Previsualiza, copia el <link> e instala tipografías de Google Fonts.",
    category: "UI",
    icon: Baseline,
    route: "/tools/font-finder",
    status: "stable",
    privacy: "server",
    tags: ["ui", "tipografia", "fuente", "fonts", "google fonts", "typography"],
  },

  // ── Research ─────────────────────────────────────────────────────────────────
  {
    id: "usability-script",
    name: "Test Script",
    description:
      "Genera guiones estructurados para tests de usabilidad moderados.",
    category: "Research",
    icon: FlaskConical,
    route: "/tools/usability-script",
    status: "stable",
    privacy: "local",
    tags: ["research", "usabilidad", "test", "guion", "entrevista"],
  },
  {
    id: "assumption-mapper",
    name: "Assumption Mapper",
    description: "Prioriza supuestos en una matriz impacto × certeza.",
    category: "Research",
    icon: Grid2X2,
    route: "/tools/assumption-mapper",
    status: "stable",
    privacy: "local",
    tags: ["research", "supuestos", "validacion", "matriz"],
  },
  {
    id: "text-analyzer",
    name: "Analizador de Texto",
    description: "Cuenta palabras, caracteres y estima el tiempo de lectura.",
    category: "Research",
    icon: Type,
    route: "/tools/text-analyzer",
    status: "stable",
    privacy: "local",
    tags: ["research", "texto", "analisis", "lectura"],
  },
  {
    id: "ab-test-calculator",
    name: "A/B Test Calculator",
    description: "Calcula significancia estadística de experimentos A/B.",
    category: "Research",
    icon: BarChart2,
    route: "/tools/ab-test-calculator",
    status: "stable",
    privacy: "local",
    tags: [
      "research",
      "ab test",
      "estadistica",
      "experimento",
      "significancia",
    ],
  },

  // ── Product Management ───────────────────────────────────────────────────────
  {
    id: "brief-builder",
    name: "Brief Builder",
    description: "Genera un design brief estructurado paso a paso.",
    category: "Product Management",
    icon: ClipboardList,
    route: "/tools/brief-builder",
    status: "stable",
    privacy: "local",
    tags: ["pm", "brief", "planificacion", "stakeholders"],
  },
  {
    id: "rice-scorer",
    name: "RICE Scorer",
    description: "Prioriza features y proyectos con el framework RICE.",
    category: "Product Management",
    icon: ListOrdered,
    route: "/tools/rice-scorer",
    status: "stable",
    privacy: "local",
    tags: ["pm", "priorizacion", "rice", "features", "roadmap"],
  },
  {
    id: "qr-generator",
    name: "Generador QR",
    description:
      "Genera códigos QR de URL, WiFi, ubicación, email, teléfono, SMS y vCard.",
    category: "Product Management",
    icon: QrCode,
    route: "/tools/qr-generator",
    status: "stable",
    privacy: "local",
    tags: ["pm", "qr", "generador", "codigo"],
  },
  {
    id: "case-converter",
    name: "Convertidor de Case",
    description: "Cambia entre camelCase, snake_case, PascalCase y más.",
    category: "Product Management",
    icon: CaseSensitive,
    route: "/tools/case-converter",
    status: "stable",
    privacy: "local",
    tags: ["pm", "texto", "case", "desarrollo", "nomenclatura"],
  },
  {
    id: "markdown-previewer",
    name: "Markdown Preview",
    description: "Escribe y previsualiza Markdown en tiempo real.",
    category: "Product Management",
    icon: FileText,
    route: "/tools/markdown-previewer",
    status: "stable",
    privacy: "local",
    tags: ["pm", "markdown", "documentacion", "preview"],
  },
];
