import { Tool } from './types';
import {
  Image as ImageIcon,
  Palette,
  Code,
  LineChart,
  LayoutTemplate,
  Eraser,
  QrCode,
  Flame,
  Pipette,
  Contrast,
  SlidersHorizontal,
  Minimize,
  RefreshCw,
  Zap,
  ArrowUpToLine,
  BoxSelect,
  PaintBucket,
  Smartphone,
  ImagePlay
} from 'lucide-react';

export const toolsRegistry: Tool[] = [
  // Imagen
  {
    id: 'background-remover',
    name: 'Remover Fondo',
    description: 'Elimina fondos de imágenes de forma automática.',
    category: 'Imagen',
    icon: Eraser,
    route: '/tools/background-remover',
    status: 'beta',
    privacy: 'local',
    tags: ['imagen', 'fondo', 'remover'],
  },
  {
    id: 'image-compressor',
    name: 'Comprimir Imagen',
    description: 'Reduce el peso de tus imágenes sin perder calidad.',
    category: 'Imagen',
    icon: Minimize,
    route: '/tools/image-compressor',
    status: 'stable',
    privacy: 'local',
    tags: ['imagen', 'comprimir', 'optimizar'],
  },
  {
    id: 'format-converter',
    name: 'Convertir Formato',
    description: 'Convierte imágenes entre diferentes formatos.',
    category: 'Imagen',
    icon: RefreshCw,
    route: '/tools/format-converter',
    status: 'stable',
    privacy: 'local',
    tags: ['imagen', 'formato', 'convertir'],
  },
  {
    id: 'image-upscaler',
    name: 'Upscaler',
    description: 'Aumenta la resolución de tus imágenes.',
    category: 'Imagen',
    icon: ArrowUpToLine,
    route: '/tools/image-upscaler',
    status: 'stable',
    privacy: 'local',
    tags: ['imagen', 'resolucion', 'upscaler'],
  },

  // Color
  {
    id: 'palette-extractor',
    name: 'Extractor de Paleta',
    description: 'Extrae la paleta de colores de cualquier imagen.',
    category: 'Color',
    icon: Pipette,
    route: '/tools/palette-extractor',
    status: 'stable',
    privacy: 'local',
    tags: ['color', 'paleta', 'extractor'],
  },
  {
    id: 'contrast-checker',
    name: 'Contraste',
    description: 'Verifica el contraste entre colores para accesibilidad.',
    category: 'Color',
    icon: Contrast,
    route: '/tools/contrast-checker',
    status: 'stable',
    privacy: 'local',
    tags: ['color', 'contraste', 'accesibilidad'],
  },
  {
    id: 'color-scale-generator',
    name: 'Escalas de Color',
    description: 'Genera escalas de color armoniosas.',
    category: 'Color',
    icon: SlidersHorizontal,
    route: '/tools/color-scale-generator',
    status: 'stable',
    privacy: 'local',
    tags: ['color', 'escala', 'generador'],
  },

  // Código
  {
    id: 'qr-generator',
    name: 'Generador QR',
    description: 'Crea códigos QR personalizados.',
    category: 'Código',
    icon: QrCode,
    route: '/tools/qr-generator',
    status: 'stable',
    privacy: 'local',
    tags: ['codigo', 'qr', 'generador'],
  },
  {
    id: 'favicon-generator',
    name: 'Generador de Favicons',
    description: 'Genera todos los formatos de favicon necesarios.',
    category: 'Código',
    icon: BoxSelect,
    route: '/tools/favicon-generator',
    status: 'coming-soon',
    privacy: 'local',
    tags: ['codigo', 'favicon', 'generador'],
  },
  {
    id: 'svg-optimizer',
    name: 'Optimizador SVG',
    description: 'Limpia y minimiza tus archivos SVG.',
    category: 'Código',
    icon: Zap,
    route: '/tools/svg-optimizer',
    status: 'stable',
    privacy: 'local',
    tags: ['codigo', 'svg', 'optimizar'],
  },

  // Análisis
  {
    id: 'heatmap-analyzer',
    name: 'Heatmap Analyzer',
    description: 'Análisis de atención visual predictiva para diseños.',
    category: 'Análisis',
    icon: Flame,
    route: '/tools/heatmap-analyzer',
    status: 'beta',
    privacy: 'server',
    tags: ['analisis', 'heatmap', 'visual'],
  },

  // Layout
  {
    id: 'mockup-generator',
    name: 'Mockups',
    description: 'Genera mockups de dispositivos rápidamente.',
    category: 'Layout',
    icon: Smartphone,
    route: '/tools/mockup-generator',
    status: 'coming-soon',
    privacy: 'local',
    tags: ['layout', 'mockup', 'generador'],
  },
  {
    id: 'placeholder-generator',
    name: 'Placeholders',
    description: 'Crea imágenes de relleno con dimensiones exactas.',
    category: 'Layout',
    icon: ImagePlay,
    route: '/tools/placeholder-generator',
    status: 'coming-soon',
    privacy: 'local',
    tags: ['layout', 'placeholder', 'generador'],
  },
  {
    id: 'gradient-generator',
    name: 'Gradientes',
    description: 'Crea y exporta gradientes CSS fácilmente.',
    category: 'Layout',
    icon: PaintBucket,
    route: '/tools/gradient-generator',
    status: 'stable',
    privacy: 'local',
    tags: ['layout', 'gradiente', 'generador'],
  }
];
