import { Tool } from './types';
import {
  Image as ImageIcon,
  Palette,
  Code,
  LineChart,
  LayoutTemplate,
  Eraser,
  QrCode,
  Flame,
  Pipette,
  Contrast,
  SlidersHorizontal,
  Minimize,
  RefreshCw,
  Zap,
  ArrowUpToLine,
  BoxSelect,
  PaintBucket,
  Smartphone,
  ImagePlay,
  Type,
  AlignLeft,
  FileText,
  CaseSensitive,
  Sparkles,
  ClipboardList,
  TextCursor,
  Ruler,
  Map,
  Grid2X2,
  FlaskConical,
} from 'lucide-react';

export const toolsRegistry: Tool[] = [
  // Imagen
  {
    id: 'background-remover',
    name: 'Remover Fondo',
    description: 'Elimina fondos de imágenes de forma automática.',
    category: 'Imagen',
    icon: Eraser,
    route: '/tools/background-remover',
    status: 'beta',
    privacy: 'local',
    tags: ['imagen', 'fondo', 'remover'],
  },
  {
    id: 'image-compressor',
    name: 'Comprimir Imagen',
    description: 'Reduce el peso de tus imágenes sin perder calidad.',
    category: 'Imagen',
    icon: Minimize,
    route: '/tools/image-compressor',
    status: 'stable',
    privacy: 'local',
    tags: ['imagen', 'comprimir', 'optimizar'],
  },
  {
    id: 'format-converter',
    name: 'Convertir Formato',
    description: 'Convierte imágenes entre diferentes formatos.',
    category: 'Imagen',
    icon: RefreshCw,
    route: '/tools/format-converter',
    status: 'stable',
    privacy: 'local',
    tags: ['imagen', 'formato', 'convertir'],
  },
  {
    id: 'image-upscaler',
    name: 'Upscaler',
    description: 'Aumenta la resolución de tus imágenes.',
    category: 'Imagen',
    icon: ArrowUpToLine,
    route: '/tools/image-upscaler',
    status: 'stable',
    privacy: 'local',
    tags: ['imagen', 'resolucion', 'upscaler'],
  },

  // Color
  {
    id: 'palette-extractor',
    name: 'Extractor de Paleta',
    description: 'Extrae la paleta de colores de cualquier imagen.',
    category: 'Color',
    icon: Pipette,
    route: '/tools/palette-extractor',
    status: 'stable',
    privacy: 'local',
    tags: ['color', 'paleta', 'extractor'],
  },
  {
    id: 'contrast-checker',
    name: 'Contraste',
    description: 'Verifica el contraste entre colores para accesibilidad.',
    category: 'Color',
    icon: Contrast,
    route: '/tools/contrast-checker',
    status: 'stable',
    privacy: 'local',
    tags: ['color', 'contraste', 'accesibilidad'],
  },
  {
    id: 'color-scale-generator',
    name: 'Escalas de Color',
    description: 'Genera escalas de color armoniosas.',
    category: 'Color',
    icon: SlidersHorizontal,
    route: '/tools/color-scale-generator',
    status: 'stable',
    privacy: 'local',
    tags: ['color', 'escala', 'generador'],
  },

  // Código
  {
    id: 'qr-generator',
    name: 'Generador QR',
    description: 'Crea códigos QR personalizados.',
    category: 'Código',
    icon: QrCode,
    route: '/tools/qr-generator',
    status: 'stable',
    privacy: 'local',
    tags: ['codigo', 'qr', 'generador'],
  },
  {
    id: 'favicon-generator',
    name: 'Generador de Favicons',
    description: 'Genera todos los formatos de favicon necesarios.',
    category: 'Código',
    icon: BoxSelect,
    route: '/tools/favicon-generator',
    status: 'coming-soon',
    privacy: 'local',
    tags: ['codigo', 'favicon', 'generador'],
  },
  {
    id: 'svg-optimizer',
    name: 'Optimizador SVG',
    description: 'Limpia y minimiza tus archivos SVG.',
    category: 'Código',
    icon: Zap,
    route: '/tools/svg-optimizer',
    status: 'stable',
    privacy: 'local',
    tags: ['codigo', 'svg', 'optimizar'],
  },

  // Análisis
  {
    id: 'heatmap-analyzer',
    name: 'Heatmap Analyzer',
    description: 'Análisis de atención visual predictiva para diseños.',
    category: 'Análisis',
    icon: Flame,
    route: '/tools/heatmap-analyzer',
    status: 'beta',
    privacy: 'server',
    tags: ['analisis', 'heatmap', 'visual'],
  },

  // Layout
  {
    id: 'mockup-generator',
    name: 'Mockups',
    description: 'Genera mockups de dispositivos rápidamente.',
    category: 'Layout',
    icon: Smartphone,
    route: '/tools/mockup-generator',
    status: 'stable',
    privacy: 'local',
    tags: ['layout', 'mockup', 'generador'],
  },
  {
    id: 'placeholder-generator',
    name: 'Placeholders',
    description: 'Crea imágenes de relleno con dimensiones exactas.',
    category: 'Layout',
    icon: ImagePlay,
    route: '/tools/placeholder-generator',
    status: 'stable',
    privacy: 'local',
    tags: ['layout', 'placeholder', 'generador'],
  },
  {
    id: 'gradient-generator',
    name: 'Gradientes',
    description: 'Crea y exporta gradientes CSS fácilmente.',
    category: 'Layout',
    icon: PaintBucket,
    route: '/tools/gradient-generator',
    status: 'stable',
    privacy: 'local',
    tags: ['layout', 'gradiente', 'generador'],
  },

  // Diseño
  {
    id: 'journey-map',
    name: 'Journey Map',
    description: 'Construye mapas de viaje del usuario con emociones, touchpoints y oportunidades.',
    category: 'Diseño',
    icon: Map,
    route: '/tools/journey-map',
    status: 'stable',
    privacy: 'local',
    tags: ['diseño', 'journey', 'mapa', 'usuario', 'experiencia', 'ux'],
  },
  {
    id: 'assumption-mapper',
    name: 'Assumption Mapper',
    description: 'Prioriza supuestos de diseño en una matriz impacto × certeza.',
    category: 'Diseño',
    icon: Grid2X2,
    route: '/tools/assumption-mapper',
    status: 'stable',
    privacy: 'local',
    tags: ['diseño', 'supuestos', 'validacion', 'matriz', 'research'],
  },
  {
    id: 'usability-script',
    name: 'Test Script',
    description: 'Genera guiones estructurados para tests de usabilidad moderados.',
    category: 'Diseño',
    icon: FlaskConical,
    route: '/tools/usability-script',
    status: 'stable',
    privacy: 'local',
    tags: ['diseño', 'usabilidad', 'test', 'guion', 'research', 'entrevista'],
  },
  {
    id: 'spacing-scale',
    name: 'Escala de Espaciado',
    description: 'Genera sistemas de espaciado en múltiplos exportables como CSS, Tailwind o tokens.',
    category: 'Diseño',
    icon: Ruler,
    route: '/tools/spacing-scale',
    status: 'stable',
    privacy: 'local',
    tags: ['diseño', 'espaciado', 'spacing', 'tokens', 'tailwind', 'sistema'],
  },
  {
    id: 'typography-scale',
    name: 'Escala Tipográfica',
    description: 'Genera escalas tipográficas modulares con ratios clásicos.',
    category: 'Diseño',
    icon: TextCursor,
    route: '/tools/typography-scale',
    status: 'stable',
    privacy: 'local',
    tags: ['diseño', 'tipografia', 'escala', 'tokens', 'sistema'],
  },
  {
    id: 'brief-builder',
    name: 'Brief Builder',
    description: 'Genera un design brief estructurado paso a paso.',
    category: 'Diseño',
    icon: ClipboardList,
    route: '/tools/brief-builder',
    status: 'stable',
    privacy: 'local',
    tags: ['diseño', 'brief', 'proceso', 'stakeholders', 'planning'],
  },

  // Escritura
  {
    id: 'case-converter',
    name: 'Convertidor de Case',
    description: 'Cambia entre camelCase, snake_case, PascalCase y más.',
    category: 'Escritura',
    icon: CaseSensitive,
    route: '/tools/case-converter',
    status: 'stable',
    privacy: 'local',
    tags: ['escritura', 'texto', 'case', 'converter'],
  },
  {
    id: 'lorem-ipsum',
    name: 'Generador Lorem Ipsum',
    description: 'Genera texto de relleno personalizado para tus diseños.',
    category: 'Escritura',
    icon: AlignLeft,
    route: '/tools/lorem-ipsum',
    status: 'stable',
    privacy: 'local',
    tags: ['escritura', 'texto', 'lorem', 'dummy'],
  },
  {
    id: 'text-analyzer',
    name: 'Analizador de Texto',
    description: 'Cuenta palabras, caracteres y estima el tiempo de lectura.',
    category: 'Escritura',
    icon: Type,
    route: '/tools/text-analyzer',
    status: 'stable',
    privacy: 'local',
    tags: ['escritura', 'texto', 'analisis', 'contador'],
  },
  {
    id: 'markdown-previewer',
    name: 'Markdown Preview',
    description: 'Escribe y previsualiza Markdown en tiempo real.',
    category: 'Escritura',
    icon: FileText,
    route: '/tools/markdown-previewer',
    status: 'stable',
    privacy: 'local',
    tags: ['escritura', 'texto', 'markdown', 'preview'],
  },
  {
    id: 'copy-assistant',
    name: 'Asistente de Copy',
    description: 'Tu experto en copywriting 100% local y privado.',
    category: 'Escritura',
    icon: Sparkles,
    route: '/tools/copy-assistant',
    status: 'stable',
    privacy: 'local',
    tags: ['escritura', 'texto', 'ai', 'copywriting', 'asistente'],
  }
];
